# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='_account_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_register_date',
            new_name='_account_register_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_passwd',
        ),
        migrations.AddField(
            model_name='account',
            name='_account_passwd',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
