# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160321_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='_account_name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='_account_passwd',
            new_name='account_passwd',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='_account_register_date',
            new_name='account_register_date',
        ),
    ]
