# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_auto_20160518_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('project_description', models.CharField(blank=True, max_length=140)),
                ('project_start_date', models.DateField()),
                ('project_expire_date', models.DateField()),
                ('project_status', models.CharField(max_length=20)),
                ('project_owner', models.CharField(max_length=30)),
                ('project_members', models.ManyToManyField(to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
                ('tag_description', models.CharField(max_length=80, unique=True)),
                ('tag_project', models.ManyToManyField(to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, unique=True)),
                ('task_description', models.CharField(blank=True, max_length=140)),
                ('task_start_date', models.DateField()),
                ('task_exipre_time', models.IntegerField()),
                ('task_status', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('task_members', models.ManyToManyField(to='accounts.Account')),
            ],
        ),
    ]
