# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(related_name='projects_project_related', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
