# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160518_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_expire_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start_date',
            field=models.DateField(blank=True),
        ),
    ]
