# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160518_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_exipre_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start_date',
            field=models.DateField(blank=True),
        ),
    ]
