# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160518_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_exipre_time',
        ),
        migrations.AddField(
            model_name='task',
            name='task_expire_time',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 5, 18, 15, 29, 59, 161326, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
