# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_project_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_applicants',
            field=models.ManyToManyField(related_name='projects_applicant_related', to='accounts.Account'),
        ),
    ]
