# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-19 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160519_0553'),
        ('projects', '0007_auto_20160519_0624'),
    ]

    operations = [
    ]
