# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160518_0619'),
        ('projects', '0009_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatQRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_openid', models.CharField(max_length=100)),
                ('qrcode_url', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
