# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_wechatqrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatqrcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='wechatqrcode',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='wechatqrcode',
            name='wechat_openid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
