# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160608_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatqrcode',
            name='qrcode_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
