# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Account')),
                ('_contactinfo_name', models.CharField(max_length=30)),
                ('_contactinfo_cellphone', models.CharField(max_length=20)),
                ('_contactinfo_email', models.CharField(max_length=30)),
                ('_contactinfo_birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_job_title', models.CharField(max_length=30)),
                ('_description', models.TextField()),
                ('_start_date', models.DateField()),
                ('_end_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_project_name', models.CharField(max_length=30)),
                ('_project_description', models.TextField()),
                ('_project_job_title', models.CharField(max_length=50)),
                ('_project_contribution', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_skill_type', models.CharField(max_length=30)),
                ('_skill_description', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
