# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill__skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='_description',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='_end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='_job_title',
            field=models.CharField(default='Null', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='_start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='_skill_description',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='_skill_type',
            field=models.CharField(default='Null', max_length=30, unique=True),
        ),
    ]
