# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160503_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='_job_title',
            field=models.CharField(default='Null', max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='_skill_type',
            field=models.CharField(default='Null', max_length=30),
        ),
    ]
