# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160503_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='_contactinfo_birthdate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
