# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_contactinfo__contactinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='_contactinfo_description',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
