# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160503_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='account',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
