# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='order',
        ),
    ]
